AWSTemplateFormatVersion: "2010-09-09"
Description: ECS Task deployment for Neo4j
Parameters:
  Image:
    Type: String
    Description: Docker Image to run
  Cluster:
      Type: String
      Description: ECS Cluster
  SubnetId:
      Type: List<AWS::EC2::Subnet::Id>
      Description: Select at two subnets in your selected VPC.
  VpcId:
      Type: String
      Description: >
        Optional - Specifies the ID of an existing VPC in which to launch
        your container instances. If you specify a VPC ID, you must specify a list of
        existing subnets in that VPC. If you do not specify a VPC ID, a new VPC is created
        with atleast 1 subnet.
      Default: ''
      AllowedPattern: "^(?:vpc-[0-9a-f]{8}|)$"
      ConstraintDescription: >
        VPC Id must begin with 'vpc-' or leave blank to have a
        new VPC created
Resources:
  ECSNeo4jTaskRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Effect: Allow
          Principal:
            Service: ecs-tasks.amazonaws.com
          Action: ['sts:AssumeRole']
      Path: /
  ECSTaskRoleInstanceProfile:
    Type: "AWS::IAM::InstanceProfile"
    Properties:
      Path: /
      Roles:
        - !Ref ECSNeo4jTaskRole
  ECSNeo4jTaskLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      RetentionInDays: 7
  ECSNeo4jTaskDefinition:
    Type: "AWS::ECS::TaskDefinition"
    Properties:
      Family: !Join [ "", [ "Neo4j-", !Ref "AWS::StackName"]]
      TaskRoleArn: !Ref ECSNeo4jTaskRole
      Volumes:
        - Name: neodata
          Host:
            SourcePath: /mnt/data/neodata
        - Name: neologs
          Host:
            SourcePath: /mnt/data/neologs
      ContainerDefinitions:
        -
          Name: !Join [ "", [ "Neo4j-", !Ref "AWS::StackName"]]
          PortMappings:
            - HostPort: 7687
              ContainerPort: 7687
              Protocol: tcp
            - HostPort: 7474
              ContainerPort: 7474
              Protocol: tcp
          Essential: true
          Environment:
            - Name: NEO4J_AUTH
              Value: neo4j/threat-buster
          Image: !Ref Image
          MountPoints:
            - ContainerPath: /data
              SourceVolume: neodata
            - ContainerPath: /logs
              SourceVolume: neologs
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Ref ECSNeo4jTaskLogGroup
              awslogs-region: !Ref AWS::Region
              awslogs-stream-prefix: neo4j
          MemoryReservation: 500
          Cpu: 0
          Ulimits:
            - HardLimit: 40000
              SoftLimit: 40000
              Name: nofile
  ECSServiceRole:
      Type: AWS::IAM::Role
      Properties:
        AssumeRolePolicyDocument:
          Statement:
          - Effect: Allow
            Principal:
              Service: [ecs.amazonaws.com]
            Action: ['sts:AssumeRole']
        Path: /
        ManagedPolicyArns:
          - arn:aws:iam::aws:policy/service-role/AmazonEC2ContainerServiceRole
  loadBalancer:
      Type: 'AWS::ElasticLoadBalancingV2::LoadBalancer'
      Properties:
        Subnets: !Ref SubnetId
        Scheme: internal
        Type: network
  ALBBoltListener:
      Type: AWS::ElasticLoadBalancingV2::Listener
      DependsOn: ECSServiceRole
      Properties:
        DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref ECSBoltTargetGroup
        LoadBalancerArn: !Ref loadBalancer
        Port: 7687
        Protocol: TCP
  ECSBoltTargetGroup:
      Type: AWS::ElasticLoadBalancingV2::TargetGroup
      Properties:
        Port: 7687
        Protocol: TCP
        VpcId: !Ref VpcId
  Service:
    DependsOn: ALBBoltListener
    Type: AWS::ECS::Service
    Properties:
      Role: !Ref ECSServiceRole
      TaskDefinition: !Ref ECSNeo4jTaskDefinition
      DesiredCount: 1
      LoadBalancers:
      - TargetGroupArn: !Ref ECSBoltTargetGroup
        ContainerPort: 7687
        ContainerName: !Join [ "", [ "Neo4j-", !Ref "AWS::StackName"]]
      Cluster: !Ref Cluster
Outputs:
  ECSTaskDefinition:
    Value: "ECSNeo4jTaskDefinition"
    Description: ECS Task Definition