AWSTemplateFormatVersion: "2010-09-09"
Description: Random String Generator
Parameters:
  Bucket:
    Type: String
    Description: Bucket Name for stored scripts
Resources:
  RandomInput:
    Type: "AWS::Lambda::Function"
    Properties:
      Handler: "lambda_function.lambda_handler"
      Role:
        Fn::GetAtt:
          - "LambdaExecutionRole"
          - "Arn"
      Code:
        S3Bucket: !Ref Bucket
        S3Key: "lambda_function.zip"
      Runtime: "python2.7"
      Timeout: "25"
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: "/"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
Outputs:
  Arn:
    Value: !GetAtt RandomInput.Arn