AWSTemplateFormatVersion: "2010-09-09"
Description: Wrapper CloudFormation Yaml Script for Threat-Buster
Parameters:
  ScriptBucket:
    Type: String
    Description: Bucket Name for stored scripts
  CertificateARN:
    Type: String
    Description: "The ARN of the certificate to use on the load balancer."
  Image:
    Type: String
    Description: The docker image
Resources:
  Vpc:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "https://s3.${AWS::Region}.amazonaws.com/${ScriptBucket}/vpc.yaml"
      TimeoutInMinutes: '60'
      Parameters:
        VpcCidr: 10.0.0.0/16
        SubnetCidr1: 10.0.0.0/24
        SubnetCidr2: 10.0.1.0/24
        SubnetCidr3: 10.0.2.0/24
        NumberOfAZs: 2
  RandomInput:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "https://s3.${AWS::Region}.amazonaws.com/${ScriptBucket}/random_input.yaml"
      TimeoutInMinutes: '60'
      Parameters:
        Bucket: cf-templates-threat-buster
  ecs:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "https://s3.${AWS::Region}.amazonaws.com/${ScriptBucket}/ecs.yaml"
      TimeoutInMinutes: '60'
      Parameters:
        SecurityGroupId: !GetAtt Vpc.Outputs.InstanceSecurityGroup
        VpcId: !GetAtt Vpc.Outputs.Vpc
        SubnetId: !GetAtt Vpc.Outputs.SubnetIds
        VpcCidr: 10.0.0.0/16
  neo4jTask:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "https://s3.${AWS::Region}.amazonaws.com/${ScriptBucket}/ecs_task_neo4j.yaml"
      TimeoutInMinutes: '60'
      Parameters:
        Image: 'neo4j:enterprise'
        SubnetId: !GetAtt Vpc.Outputs.SubnetIds
        Cluster: !GetAtt ecs.Outputs.Cluster
        VpcId: !GetAtt Vpc.Outputs.Vpc
        ECSALBSecurityGroup: !GetAtt ecs.Outputs.ECSALBSecurityGroup
  DBPassword:
    Type: AWS::CloudFormation::CustomResource
    DependsOn: RandomInput
    Properties:
      Length: 25
      Punctuation: true
      RDSCompatible: true
      ServiceToken: !GetAtt RandomInput.Outputs.Arn