AWSTemplateFormatVersion: "2010-09-09"
Description: Wrapper CloudFormation Yaml Script for Threat-Buster
Parameters:
  Bucket:
    Type: String
    Description: Bucket Name for stored scripts
  CertificateARN:
    Type: String
    Description: "The ARN of the certificate to use on the load balancer."
Resources:
  Vpc:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.eu-west-2.amazonaws.com/cf-templates-threat-buster/vpc.yaml
      TimeoutInMinutes: '60'
      Parameters:
        VpcCidr: 10.0.0.0/16
        SubnetCidr1: 10.0.0.0/24
        SubnetCidr2: 10.0.1.0/24
        SubnetCidr3: 10.0.2.0/24
        NumberOfAZs: 2
  RandomInput:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.eu-west-2.amazonaws.com/cf-templates-threat-buster/random_input.yaml
      TimeoutInMinutes: '60'
      Parameters:
        Bucket: cf-templates-threat-buster
  ecs:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.eu-west-2.amazonaws.com/cf-templates-threat-buster/ecs.yaml
      TimeoutInMinutes: '60'
      Parameters:
        SecurityGroupId: !GetAtt Vpc.Outputs.InstanceSecurityGroup
        VpcId: !GetAtt Vpc.Outputs.Vpc
        SubnetId: !GetAtt Vpc.Outputs.SubnetIds
        SecurityIngressFromPort: 8182
        SecurityIngressToPort: 8182
  ecsTask:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.eu-west-2.amazonaws.com/cf-templates-threat-buster/ecs_task.yaml
      TimeoutInMinutes: '60'
      Parameters:
        DynamoTablePrefix: !Join [ "", [jg, !Ref "AWS::StackName" ]]
        Image: !Sub
          - "${account}.dkr.ecr.${region}.amazonaws.com/${repo}:latest"
          - account: !Ref AWS::AccountId
            region: !Ref AWS::Region
            repo: !GetAtt ecs.Outputs.Repository
        SubnetId: !GetAtt Vpc.Outputs.SubnetIds
  DynamoTables:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.eu-west-2.amazonaws.com/cf-templates-threat-buster/dynamodb-janusgraph-tables-multiple.yaml
      TimeoutInMinutes: '60'
      Parameters:
        TablePrefix: !Join [ "", [jg, !Ref "AWS::StackName" ]]
  DBPassword:
    Type: AWS::CloudFormation::CustomResource
    DependsOn: RandomInput
    Properties:
      Length: 25
      Punctuation: true
      RDSCompatible: true
      ServiceToken: !GetAtt RandomInput.Outputs.Arn
  ThreatBuster:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.eu-west-2.amazonaws.com/cf-templates-threat-buster/rds.yaml
      TimeoutInMinutes: '60'
      Parameters:
        DBUser: threatbuster
        DBPassword: !GetAtt DBPassword.RandomString
        BaseName: threatbuster
        DNSName: bob
        CertificateARN: !Ref CertificateARN
        VpcId: !GetAtt Vpc.Outputs.Vpc
        SubnetId: !GetAtt Vpc.Outputs.SubnetIds
        SecurityGroupId: !GetAtt Vpc.Outputs.InstanceSecurityGroup
Outputs:
  TaskRunCmd:
    Value: !Sub "aws ecs run-task --cluster ${ecs.Outputs.Cluster} --task-definition ${ecsTask.Outputs.ECSTaskDefinition} --region ${AWS::Region}"
    Description: Command to run task
